name: WorldGuard Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload WorldGuard bukkit artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          path: ./worldguard-bukkit/build/libs/*
